# Tugas 1

In [6]:
# import library
import numpy as np
import pandas as pd
import seaborn as sb
%matplotlib inline
import matplotlib.pyplot as plt
import math

In [7]:
#menampilkan data
data = pd.read_csv("https://raw.githubusercontent.com/Ahmad-Dani-Kurniawan/datamining/main/data-jumlah-penduduk-berdasarkan-pendidikan-tahun-2013.csv")
print(data)

      tahun         nama_provinsi nama_kabupaten_kota   nama_kecamatan  \
0      2013  PROVINSI DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU UTR
1      2013  PROVINSI DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU UTR
2      2013  PROVINSI DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU UTR
3      2013  PROVINSI DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SLT
4      2013  PROVINSI DKI JAKARTA  KAB.ADM.KEP.SERIBU  KEP. SERIBU SLT
...     ...                   ...                 ...              ...
2665   2013  PROVINSI DKI JAKARTA       JAKARTA TIMUR         CIPAYUNG
2666   2013  PROVINSI DKI JAKARTA       JAKARTA TIMUR         CIPAYUNG
2667   2013  PROVINSI DKI JAKARTA       JAKARTA TIMUR         CIPAYUNG
2668   2013  PROVINSI DKI JAKARTA       JAKARTA TIMUR         CIPAYUNG
2669   2013  PROVINSI DKI JAKARTA       JAKARTA TIMUR         CIPAYUNG

      nama_kelurahan           pendidikan  jumlah
0        P. PANGGANG  Tidak/Belum Sekolah  1201.0
1          P. KELAPA  Tidak/Belum Sekolah  1189.0
2         P. HARAPAN  Tidak/Belum Sekolah   419.0
3     P. UNTUNG JAWA  Tidak/Belum Sekolah   434.0
4          P. TIDUNG  Tidak/Belum Sekolah   892.0
...              ...                  ...     ...
2665          MUNJUL           Strata III     9.0
2666            SETU           Strata III    16.0
2667      BAMBU APUS           Strata III    15.0
2668    LUBANG BUAYA           Strata III    19.0
2669           CEGER           Strata III     9.0

[2670 rows x 7 columns]

In [8]:
#menampilkan 5 baris data pertama
data.head()

,tahun,nama_provinsi,nama_kabupaten_kota,nama_kecamatan,nama_kelurahan,pendidikan,jumlah
0,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. PANGGANG,Tidak/Belum Sekolah,1201.0
1,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. KELAPA,Tidak/Belum Sekolah,1189.0
2,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. HARAPAN,Tidak/Belum Sekolah,419.0
3,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU SLT,P. UNTUNG JAWA,Tidak/Belum Sekolah,434.0
4,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU SLT,P. TIDUNG,Tidak/Belum Sekolah,892.0

In [9]:
# 1. 
def dt1(i,j):
  P = 6
  Q = 0
  for col in [""nama_provinsi", "nama_kabupaten_kota", "nama_kecamatan", "nama_kelurahan", "pendidikan"]:
    if data[col][i] == data[col][j]:
      Q += 1
  return (P-Q)/P

In [10]:
print(dt1(1,2))
print(dt1(1,3))
print(dt1(1,4))

0.16666666666666666
0.3333333333333333
0.3333333333333333

In [ ]:
def dt2(i,j,h):
  result = 0
  for col in ["jumlah"]:
    result = math.pow(abs(data[col][i] - data[col][j]), h)
  return result**(1/h)

In [ ]:
# Manhattan distance
print(dt2(1,2,1))
print(dt2(1,3,1))
print(dt2(1,4,1))

In [ ]:
# Euclidean distance
print(dt2(1,2,2))
print(dt2(1,3,2))
print(dt2(1,4,2))

There is a lot more that you can do with outputs (such as including interactive outputs)
with your book. For more information about this, see [the Jupyter Book documentation](https://jupyterbook.org)